# Generated by Django 4.0.4 on 2022-05-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oblast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Область')),
                ('slug', models.SlugField(unique=True, verbose_name='SLUG')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Області',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gromada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='SLUG')),
                ('tg_type', models.CharField(choices=[('misto', 'міська'), ('sel', 'селищна'), ('selo', 'сільська')], max_length=255, verbose_name='Тип')),
                ('portal_url', models.URLField(blank=True, max_length=400, verbose_name='Посилання на геопортал')),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/', verbose_name='Зображення')),
                ('area', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Площа')),
                ('type_geoportal', models.CharField(choices=[('public', 'Публічний'), ('permission', 'Службовий')], max_length=255, verbose_name='Тип доступу до геопорталу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Запис створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Запис оновлено')),
                ('views', models.IntegerField(blank=True, verbose_name='Переглядів')),
                ('oblast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gromada', to='otgalbum.oblast', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Громада',
                'verbose_name_plural': 'Громади',
                'ordering': ['-created'],
            },
        ),
    ]
