# Generated by Django 4.0.4 on 2022-05-06 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otgalbum', '0002_remove_gromada_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='gromada',
            name='created_for',
            field=models.ManyToManyField(blank=True, related_name='Користувач', to=settings.AUTH_USER_MODEL),
        ),
    ]
