# Generated by Django 4.0.4 on 2022-05-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otgalbum', '0003_gromada_created_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gromada',
            name='tg_type',
            field=models.CharField(choices=[('міська', 'міська'), ('селищна', 'селищна'), ('сільська', 'сільська')], max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='gromada',
            name='type_geoportal',
            field=models.CharField(choices=[('Публічний', 'Публічний'), ('Службовий', 'Службовий')], max_length=255, verbose_name='Тип доступу'),
        ),
    ]
