# Generated by Django 4.0.4 on 2022-05-06 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otgalbum', '0004_alter_gromada_tg_type_alter_gromada_type_geoportal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gromada',
            name='created_for',
        ),
        migrations.RemoveField(
            model_name='gromada',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gromada',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gromada',
            name='portal_url',
        ),
        migrations.RemoveField(
            model_name='gromada',
            name='type_geoportal',
        ),
        migrations.RemoveField(
            model_name='gromada',
            name='views',
        ),
        migrations.CreateModel(
            name='Geoportal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_geoportal', models.CharField(choices=[('Публічний', 'Публічний'), ('Службовий', 'Службовий')], max_length=255, verbose_name='Тип доступу')),
                ('portal_url', models.URLField(blank=True, max_length=400, verbose_name='Посилання на геопортал')),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/', verbose_name='Зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('views', models.IntegerField(blank=True, verbose_name='Переглядів')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Запис створено')),
                ('created_for', models.ManyToManyField(blank=True, related_name='Користувач', to=settings.AUTH_USER_MODEL)),
                ('gromada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geoportal', to='otgalbum.oblast', verbose_name='Громада')),
            ],
            options={
                'verbose_name': 'Геопортал',
                'verbose_name_plural': 'Геопортали',
                'ordering': ['-created'],
            },
        ),
    ]
